import { SUPPORTED_JOB_TYPES, normalizeJobType } from './taskTypes.js';

export const VALID_PROMOTION_POLICIES = new Set(['auto_promote', 'auto_accept', 'manual']);

export const MUTATION_CAPABLE_JOBS = new Set([
  SUPPORTED_JOB_TYPES.FACTION_POLITICS_REFINEMENT,
  SUPPORTED_JOB_TYPES.LOCATION_HIERARCHY_REFINEMENT,
  SUPPORTED_JOB_TYPES.MACRO_HISTORY_TIMELINE,
  SUPPORTED_JOB_TYPES.CHARACTER_FAMILY_LINEAGE,
  SUPPORTED_JOB_TYPES.REGION_GEOPOLITICS,
]);

export const APPEND_ONLY_DIMENSIONS = new Set([
  'bestiary',
  'cultures',
  'languages',
  'religions',
]);

function envFlag(val, fallback = false) {
  if (val == null) return fallback;
  return ['1', 'true', 'yes', 'on'].includes(String(val).toLowerCase());
}

/**
 * Affirmative-only server trust verification.
 * Trust is NEVER inferred from task description JSON or markdown.
 * It must come from verified server-side task creator/author properties.
 */
export function isTrustedOperator(task = {}) {
  // If task was generated by a cycle/harvester, it is untrusted
  if (task.cycleId || task.sourceDraftId || task.threadFingerprint) return false;

  const trustedCreators = new Set(['operator', 'human', 'jimmothy', 'admin']);
  const creator = String(task.created_by || task.creator || task.author || '').toLowerCase();

  return trustedCreators.has(creator);
}

/**
 * Validates whether an entity name collides with an existing protected entity name
 * to prevent shadow-entity spoofing under new IDs.
 */
export function detectShadowEntityCollision(candidateEntities = [], knownEntities = []) {
  const protectedNames = new Set(
    knownEntities
      .filter((e) => e && (e.is_protected === true || e.isProtected === true))
      .map((e) => String(e.name || '').trim().toLowerCase())
      .filter(Boolean),
  );

  for (const candidate of candidateEntities) {
    if (!candidate || !candidate.name) continue;
    const normName = String(candidate.name).trim().toLowerCase();
    if (protectedNames.has(normName)) {
      return { collides: true, name: candidate.name };
    }
  }

  return { collides: false };
}

/**
 * Resolves the final promotion policy for a draft based on:
 * 1. Master global capability switch
 * 2. Hard canon protection & fail-closed mutation checks
 * 3. Explicit operator task override
 * 4. Job-type scoped default
 * 5. Universe / project default
 */
export function resolvePromotionPolicy({
  story = {},
  task = {},
  taskMetadata = {},
  jobType: rawJobType,
  context = {},
  generatedPayload = null,
} = {}) {
  const jobType = normalizeJobType(rawJobType || taskMetadata.jobType);
  const globalAutoPromoteEnabled = envFlag(process.env.STORYTIME_HARNESS_AUTO_PROMOTE, true);

  // Reject 'quarantine' as an input policy
  if (taskMetadata.promotionPolicy === 'quarantine') {
    throw new Error("Invalid promotion policy: 'quarantine' is a runtime outcome, not a selectable policy.");
  }

  if (story.promotion_policy === 'quarantine') {
    throw new Error("Invalid universe promotion policy: 'quarantine' is a runtime outcome, not a selectable policy.");
  }

  // 1. HARD CANON PROTECTION GUARD
  const allKnownEntities = [
    ...(context.characters || []),
    ...(context.factions || []),
    ...(context.locations || []),
    ...(context.storyArcs || []),
    ...(context.timelineEvents || []),
    ...(context.canonRelationships || []),
  ];

  const protectedEntityIds = new Set(
    allKnownEntities
      .filter((e) => e && (e.is_protected === true || e.isProtected === true))
      .map((e) => String(e.id || e.source_id || '')),
  );

  if (story.is_protected === true) {
    protectedEntityIds.add(String(story.id));
  }

  // 2. FAIL-CLOSED CHECK: Mutation-capable job must explicitly declare mayUpdate when protected entities exist
  if (MUTATION_CAPABLE_JOBS.has(jobType) && protectedEntityIds.size > 0) {
    const mayUpdate = taskMetadata.mayUpdate;
    if (!mayUpdate || !Array.isArray(mayUpdate) || mayUpdate.length === 0) {
      return {
        policy: 'manual',
        reason: 'fail_closed_missing_may_update',
        details: `Job type ${jobType} is mutation-capable but task metadata lacks declared mayUpdate array in a universe with protected entities.`,
      };
    }
  }

  // Check if mayUpdate targets any protected entity
  const requestedUpdates = Array.isArray(taskMetadata.mayUpdate) ? taskMetadata.mayUpdate.map(String) : [];
  const touchesProtected = requestedUpdates.some((id) => protectedEntityIds.has(id));

  // Check shadow-entity collision against protected names
  const candidateCreates = Array.isArray(taskMetadata.mayCreate)
    ? taskMetadata.mayCreate.map((item) => (typeof item === 'string' ? { name: item } : item))
    : [];
  const shadowCheck = detectShadowEntityCollision(candidateCreates, allKnownEntities);

  if (touchesProtected || shadowCheck.collides) {
    // Check if operator override is valid and verified server-side
    const trusted = isTrustedOperator(task);
    const hasOverride = taskMetadata.protectedOverride === true;

    if (trusted && hasOverride) {
      // Trusted operator explicitly approved override
      return {
        policy: 'auto_promote',
        reason: 'trusted_operator_protected_override',
      };
    }

    return {
      policy: 'manual',
      reason: 'protected_canon_mutation_requires_review',
      details: touchesProtected
        ? `Task mayUpdate targets protected canon entity.`
        : `Generated entity name collides with protected entity: "${shadowCheck.name}".`,
    };
  }

  // 3. APPEND-ONLY TABLE MUTATION CHECK
  if (generatedPayload) {
    // If payload attempts to mutate existing rows in append-only tables
    for (const dim of APPEND_ONLY_DIMENSIONS) {
      if (Array.isArray(generatedPayload[dim])) {
        const knownDimIds = new Set((context[dim] || []).map((e) => String(e.id)));
        for (const item of generatedPayload[dim]) {
          if (item?.id && knownDimIds.has(String(item.id))) {
            return {
              policy: 'manual',
              reason: 'append_only_table_mutation_disallowed',
              details: `Attempted to update existing entity in append-only dimension: ${dim} (${item.id})`,
            };
          }
        }
      }
    }
  }

  // 4. EXPLICIT OPERATOR TASK OVERRIDE
  if (taskMetadata.promotionPolicy && VALID_PROMOTION_POLICIES.has(taskMetadata.promotionPolicy)) {
    let resolved = taskMetadata.promotionPolicy;
    if (resolved === 'auto_promote' && !globalAutoPromoteEnabled) {
      resolved = 'auto_accept';
    }
    return { policy: resolved, reason: 'explicit_task_override' };
  }

  // 5. JOB-TYPE SCOPED DEFAULT
  if (jobType === SUPPORTED_JOB_TYPES.CHAPTER_PROSE_COMPOSITION) {
    return { policy: 'auto_accept', reason: 'job_type_default' };
  }

  // 6. UNIVERSE / PROJECT DEFAULT
  let projectPolicy = story.promotion_policy || 'auto_promote';
  if (!VALID_PROMOTION_POLICIES.has(projectPolicy)) {
    projectPolicy = 'auto_promote';
  }

  if (projectPolicy === 'auto_promote' && !globalAutoPromoteEnabled) {
    projectPolicy = 'auto_accept';
  }

  return { policy: projectPolicy, reason: 'project_default' };
}
