ALTER TABLE factions ADD COLUMN IF NOT EXISTS doctrine TEXT;
ALTER TABLE factions ADD COLUMN IF NOT EXISTS economic_leverage TEXT;
ALTER TABLE factions ADD COLUMN IF NOT EXISTS corporate_structure TEXT;
ALTER TABLE factions ADD COLUMN IF NOT EXISTS assets TEXT NOT NULL DEFAULT '[]';
